const highlightScales = {
    MajorScale: {
        C: ["C", "D", "E", "F2", "G2", "A2", "B2", "C2"],
        C_Db: ["C_Db", "D_Eb", "F2", "F_Gb2", "G_Ab2", "A_Bb2", "C2", "C_Db2"],
        D: ["D", "E", "F_Gb2", "G2", "A2", "B2", "C_Db2", "D2"],
        D_Eb: ["D_Eb", "F2", "G2", "G_Ab2", "A_Bb2", "C2", "D2", "D_Eb2"],
        E: ["E", "F_Gb2", "G_Ab2", "A2", "B2", "C_Db2", "D_Eb2", "E2"],
        F: ["F", "G", "A", "A_Bb", "C", "D", "E", "F2"],
        F_Gb: ["F_Gb", "G_Ab", "A_Bb", "B", "C_Db", "D_Eb", "F2", "F_Gb2"],
        G: ["G", "A", "B", "C", "D", "E", "F_Gb2", "G2"],
        G_Ab: ["G_Ab", "A_Bb", "C", "C_Db", "D_Eb", "F2", "G2", "G_Ab2"],
        A: ["A", "B", "C_Db", "D", "E", "F_Gb2", "G_Ab2", "A2"],
        A_Bb: ["A_Bb", "C", "D", "D_Eb", "F2", "G2", "A2", "A_Bb2"],
        B: ["B", "C_Db", "D_Eb", "E", "F_Gb2", "G_Ab2", "A_Bb2", "B2"],
    },
    MinorNatural: {
        C: ["C", "D", "D_Eb", "F2", "G2", "G_Ab2", "A_Bb2", "C2"],
        C_Db: ["C_Db", "D_Eb", "E", "F_Gb2", "G_Ab2", "A2", "B2", "C_Db2"],
        D: ["D", "E", "F2", "G2", "A2", "A_Bb2", "C2", "D2"],
        D_Eb: ["D_Eb", "F2", "F_Gb2", "G_Ab2", "A_Bb2", "B2", "C_Db2", "D_Eb2"],
        E: ["E", "F_Gb2", "G2", "A2", "B2", "C2", "D2", "E2"],
        F: ["F", "G", "G_Ab", "A_Bb", "C", "C_Db", "D_Eb", "F2"],
        F_Gb: ["F_Gb", "G_Ab", "A", "B", "C_Db", "D", "E", "F_Gb2"],
        G: ["G", "A", "A_Bb", "C", "D", "D_Eb", "F2", "G2"],
        G_Ab: ["G_Ab", "A_Bb", "B", "C_Db", "D_Eb", "E", "F_Gb2", "G_Ab2"],
        A: ["A", "B", "C", "D", "E", "F2", "G2", "A2"],
        A_Bb: ["A_Bb", "C", "C_Db", "D_Eb", "F2", "F_Gb2", "G_Ab2", "A_Bb2"],
        B: ["B", "C_Db", "D", "E", "F_Gb2", "G2", "A2", "B2"],
    },
    MinorMelodic: {
        C: ["C", "D", "D_Eb", "F2", "G2", "A2", "B2", "C2"],
        C_Db: ["C_Db", "D_Eb", "E", "F_Gb2", "G_Ab2", "A_Bb2", "C2", "C_Db2"],
        D: ["D", "E", "F2", "G2", "A2", "B2", "C_Db2", "D2"],
        D_Eb: ["D_Eb", "F2", "F_Gb2", "G_Ab2", "A_Bb2", "C2", "D2", "D_Eb2"],
        E: ["E", "F_Gb2", "G2", "A2", "B2", "C_Db2", "D_Eb2", "E2"],
        F: ["F", "G", "G_Ab", "A_Bb", "C", "D", "E", "F2"],
        F_Gb: ["F_Gb", "G_Ab", "A", "B", "C_Db", "D_Eb", "F2", "F_Gb2"],
        G: ["G", "A", "A_Bb", "C", "D", "E", "F_Gb2", "G2"],
        G_Ab: ["G_Ab", "A_Bb", "B", "C_Db", "D_Eb", "F2", "G2", "G_Ab2"],
        A: ["A", "B", "C", "D", "E", "F_Gb2", "G_Ab2", "A2"],
        A_Bb: ["A_Bb", "C", "C_Db", "D_Eb", "F2", "G2", "A2", "A_Bb2"],
        B: ["B", "C_Db", "D", "E", "F_Gb2", "G_Ab2", "A_Bb2", "B2"],
    },
    MajorHarmonic: {
        C: ["C", "D", "E", "F2", "G2", "G_Ab2", "B2", "C2"],
        C_Db: ["C_Db", "D_Eb", "F2", "F_Gb2", "G_Ab2", "A2", "C2", "C_Db2"],
        D: ["D", "E", "F_Gb2", "G2", "A2", "A_Bb2", "C_Db2", "D2"],
        D_Eb: ["D_Eb", "F2", "G2", "G_Ab2", "A_Bb2", "B2", "D2", "D_Eb2"],
        E: ["E", "F_Gb2", "G_Ab2", "A2", "B2", "C2", "D_Eb2", "E2"],
        F: ["F", "G", "A", "A_Bb", "C", "C_Db", "E", "F2"],
        F_Gb: ["F_Gb", "G_Ab", "A_Bb", "B", "C_Db", "D", "F2", "F_Gb2"],
        G: ["G", "A", "B", "C", "D", "D_Eb", "F_Gb2", "G2"],
        G_Ab: ["G_Ab", "A_Bb", "C", "C_Db", "D_Eb", "E", "G2", "G_Ab2"],
        A: ["A", "B", "C_Db", "D", "E", "F2", "G_Ab2", "A"],
        A_Bb: ["A_Bb", "C", "D", "D_Eb", "F2", "F_Gb2", "A2", "A_Bb2"],
        B: ["B", "C_Db", "D_Eb", "E", "F_Gb2", "G2", "A_Bb2", "B2"],
    },
    MinorHarmonic: {
        C: ["C", "D", "D_Eb", "F2", "G2", "G_Ab2", "B2", "C2"],
        C_Db: ["C_Db", "D_Eb", "E", "F_Gb2", "G_Ab2", "A2", "C2", "C_Db2"],
        D: ["D", "E", "F2", "G2", "A2", "A_Bb2", "C_Db2", "D2"],
        D_Eb: ["D_Eb", "F2", "F_Gb2", "G_Ab2", "A_Bb2", "B2", "D2", "D_Eb2"],
        E: ["E", "F_Gb2", "G2", "A2", "B2", "C2", "D_Eb2", "E2"],
        F: ["F", "G", "F_Ab", "A_Bb", "C", "C_Db", "E", "F2"],
        F_Gb: ["F_Gb", "G_Ab", "A", "B", "C_Db", "D", "F2", "F_Gb2"],
        G: ["G", "A", "A_Bb", "C", "D", "D_Eb", "F_Gb2", "G2"],
        G_Ab: ["G_Ab", "A_Bb", "B", "C_Db", "D_Eb", "E", "G2", "G_Ab2"],
        A: ["A", "B", "C", "D", "E", "F2", "G_Ab2", "A2"],
        A_Bb: ["A_Bb", "C", "C_Db", "D_Eb", "F2", "F_Gb2", "A2", "A_Bb2"],
        B: ["B", "C_Db", "D", "E", "F_Gb2", "G2", "A_Bb2", "B2"],
    },
    MajorPentatonic: {
        C: ["C", "D", "E", "G2", "A2", "C2"],
        C_Db: ["C_Db", "D_Eb", "F2", "G_Ab2", "A_Bb2", "C_Db2"],
        D: ["D", "E", "F_Gb2", "A2", "B2", "D2"],
        D_Eb: ["D_Eb", "F2", "G2", "A_Bb2", "C2", "D_Eb2"],
        E: ["E", "F_Gb2", "G_Ab2", "B2", "C_Db2", "E2"],
        F: ["F", "G", "A", "C", "D", "F2"],
        F_Gb: ["F_Gb", "G_Ab", "A_Bb", "C_Db", "D_Eb", "F_Gb2"],
        G: ["G", "A", "B", "D", "E", "G2"],
        G_Ab: ["G_Ab", "A_Bb", "C", "D_Eb", "F2", "G_Ab2"],
        A: ["A", "B", "C_Db", "E", "F_Gb2", "A2"],
        A_Bb: ["A_Bb", "C", "D", "F2", "G2", "A_Bb2"],
        B: ["B", "C_Db", "D_Eb", "F_Gb2", "A_Bb2", "B2"],
    },
    MinorPentatonic: {
        C: ["C", "D_Eb", "F2", "G2", "A_Bb2", "C2"],
        C_Db: ["C_Db", "E", "F_Gb2", "G_Ab2", "B2", "C_Db2"],
        D: ["D", "F2", "G2", "A2", "C2", "D2"],
        D_Eb: ["D_Eb", "F_Gb2", "G_Ab2", "A_Bb2", "C_Db2", "D_Eb2"],
        E: ["E", "G2", "A2", "B2", "D2", "E2"],
        F: ["F", "G_Ab", "A_Bb", "C", "D_Eb", "F2"],
        F_Gb: ["F_Gb", "A", "B", "C_Db", "E", "F_Gb2"],
        G: ["G", "A_Bb", "C", "D", "F2", "G2"],
        G_Ab: ["G_Ab", "B", "C_Db", "D_Eb", "F_Gb2", "G_Ab2"],
        A: ["A", "C", "D", "E", "G2", "A2"],
        A_Bb: ["A_Bb", "C_Db", "D_Eb", "F2", "G_Ab2", "A_Bb2"],
        B: ["B", "D", "E", "F_Gb2", "A2", "B2"],
    },
    MajorBlues: {
        C: ["C", "D", "D_Eb", "E", "G2", "A2", "C2"],
        C_Db: ["C_Db", "D_Eb", "E", "F2", "G_Ab2", "A_Bb2", "C_Db2"],
        D: ["D", "E", "F2", "F_Gb2", "A2", "B2", "D2"],
        D_Eb: ["D_Eb", "F2", "F_Gb2", "G2", "A_Bb2", "C2", "D_Eb2"],
        E: ["E", "F_Gb2", "G2", "G_Ab2", "B2", "C_Db2", "E2"],
        F: ["F", "G", "G_Ab", "A", "C", "D", "F2"],
        F_Gb: ["F_Gb", "G_Ab", "A", "A_Bb", "C_Db", "D_Eb", "F_Gb2"],
        G: ["G", "A", "A_Bb", "D", "E", "G2"],
        G_Ab: ["G_Ab", "A_Bb", "B", "C", "D_Eb", "F2", "G_Ab2"],
        A: ["A", "B", "C", "C_Db", "E", "F_Gb2", "A"],
        A_Bb: ["A_Bb", "C", "C_Db", "D", "F2", "G2", "A_Bb2"],
        B: ["B", "C_Db", "D", "D_Eb", "F_Gb2", "G_Ab2", "B2"],
    },
    MinorBlues: {
        C: ["C", "D_Eb", "F2", "F_Gb2", "G2", "A_Bb2", "C2"],
        C_Db: ["C_Db", "E", "F_Gb2", "G2", "G_Ab2", "B2", "C_Db2"],
        D: ["D", "F2", "G2", "G_Ab2", "A2", "C2", "D2"],
        D_Eb: ["D_Eb", "F_Gb2", "G_Ab2", "A2", "A_Bb2", "C_Db2", "D_Eb2"],
        E: ["E", "G2", "A2", "A_Bb2", "B2", "D2", "E2"],
        F: ["F", "G_Ab", "A_Bb", "B", "C", "D_Eb", "F2"],
        F_Gb: ["F_Gb", "A", "B", "C", "C_Db", "E", "F_Gb2"],
        G: ["G", "A_Bb", "C", "C_Db", "D", "F", "G2"],
        G_Ab: ["G_Ab", "B", "C_Db", "D", "D_Eb", "F_Gb2", "G_Ab2"],
        A: ["A", "C", "D", "D_Eb", "E", "G2", "A2"],
        A_Bb: ["A_Bb", "C_Db", "D_Eb", "E", "F2", "G_Ab2", "A_Bb2"],
        B: ["B", "D", "E", "F2", "F_Gb2", "A2", "B2"],
    },
};
export default highlightScales;